# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

#build:
#  command: jekyll build
#  commandOrigin: ui
#  publish: /opt/build/repo/_site

# Setup
title:               joseph ruocco
tagline:             ''
description:         ''
url:                 https://josephruocco.net
baseurl:             'https://josephruocco.net'
plugins:
  - jekyll-paginate
paginate:            10

# About/contact
author:
  name:              Joseph Ruocco
  url:               https://josephruocco.net
  email:             joe@josephruocco.net

# Custom vars
version:             1.0.0

